'use client';

import { useEffect, useMemo, useState } from 'react';

type ExamQuestion={section:'Listening'|'Reading'|'Writing';prompt:string;audio?:string;choices?:string[];answer:string;explanation:string};
const BANK:Record<number,ExamQuestion[]>={
  1:[{section:'Listening',prompt:'What greeting do you hear?',audio:'你好',choices:['Hello','Goodbye','Thank you'],answer:'Hello',explanation:'你好 is the standard greeting.'},{section:'Reading',prompt:'Choose “I am a student.”',choices:['我是学生。','我喝学生。','学生很好吃。'],answer:'我是学生。',explanation:'我是学生 uses 是 to identify the subject.'},{section:'Writing',prompt:'Type the Hanzi for “China”.',answer:'中国',explanation:'China is written 中国.'}],
  2:[{section:'Listening',prompt:'Where does the speaker want to go?',audio:'我想去火车站。',choices:['Train station','Hospital','Restaurant'],answer:'Train station',explanation:'火车站 means train station.'},{section:'Reading',prompt:'Choose the natural sequence.',choices:['我先吃饭，然后学习。','我然后先学习吃饭。','先我然后。'],answer:'我先吃饭，然后学习。',explanation:'先…然后… shows ordered actions.'},{section:'Writing',prompt:'Type the missing word: 今天___昨天冷。',answer:'比',explanation:'A 比 B + adjective makes a comparison.'}],
  3:[{section:'Listening',prompt:'Why was the match cancelled?',audio:'因为下雨，所以比赛取消了。',choices:['Rain','Traffic','Illness'],answer:'Rain',explanation:'因为下雨 gives the reason.'},{section:'Reading',prompt:'What does “越来越方便” mean?',choices:['More and more convenient','Less expensive','Already finished'],answer:'More and more convenient',explanation:'越来越 marks a continuing change.'},{section:'Writing',prompt:'Complete: 虽然很累，___他还在工作。',answer:'但是',explanation:'虽然 commonly pairs with 但是.'}],
  4:[{section:'Listening',prompt:'What is being recommended?',audio:'我建议你提前预约。',choices:['Reserve in advance','Cancel today','Pay cash'],answer:'Reserve in advance',explanation:'提前预约 means reserve in advance.'},{section:'Reading',prompt:'“值得考虑” means…',choices:['Worth considering','Impossible to finish','Already rejected'],answer:'Worth considering',explanation:'值得 means worthy of.'},{section:'Writing',prompt:'Complete: 只要坚持，___会进步。',answer:'就',explanation:'只要…就… expresses a sufficient condition.'}],
  5:[{section:'Listening',prompt:'What concern is mentioned?',audio:'这个方案可能会增加技术债务。',choices:['Technical debt','Tuition','Weather'],answer:'Technical debt',explanation:'技术债务 means technical debt.'},{section:'Reading',prompt:'“结果仍有待验证” means…',choices:['Results still need verification','Results are final','Experiment was cancelled'],answer:'Results still need verification',explanation:'有待 means remains to be done.'},{section:'Writing',prompt:'Complete: 与其等待，___马上行动。',answer:'不如',explanation:'与其…不如… expresses preference.'}],
  6:[{section:'Listening',prompt:'What is the speaker evaluating?',audio:'我们必须权衡效率与隐私之间的关系。',choices:['Efficiency and privacy','Price and color','Travel and weather'],answer:'Efficiency and privacy',explanation:'权衡 means weigh or balance.'},{section:'Reading',prompt:'“该结论未免过于武断” suggests the conclusion is…',choices:['Too arbitrary','Well supported','Easy to understand'],answer:'Too arbitrary',explanation:'未免过于武断 criticizes an overly arbitrary claim.'},{section:'Writing',prompt:'Complete: 即使遇到困难，___不能放弃。',answer:'也',explanation:'即使…也… means even if…still….'}]
};

const EXTENDED_BANK:Record<number,ExamQuestion[]>={
  1:[{section:'Listening',prompt:'Which number do you hear?',audio:'三',choices:['One','Two','Three'],answer:'Three',explanation:'三 means three.'},{section:'Reading',prompt:'Which sentence means “She is my friend”?',choices:['她是我的朋友。','她喝我的朋友。','我朋友三。'],answer:'她是我的朋友。',explanation:'她 + 是 + 我的朋友 identifies her as my friend.'},{section:'Writing',prompt:'Type the Hanzi for “person”.',answer:'人',explanation:'Person is written 人.'}],
  2:[{section:'Listening',prompt:'What time is mentioned?',audio:'我们下午两点见。',choices:['2 p.m.','3 p.m.','Tomorrow morning'],answer:'2 p.m.',explanation:'下午两点 means 2 p.m.'},{section:'Reading',prompt:'Choose “The book is on the table.”',choices:['书在桌子上。','桌子在书里。','书去桌子。'],answer:'书在桌子上。',explanation:'在…上 locates the book on top of the table.'},{section:'Writing',prompt:'Complete: 我___坐地铁去学校。',answer:'每天',explanation:'每天 means every day and fits before the verb phrase.'}],
  3:[{section:'Listening',prompt:'What did the speaker forget?',audio:'我忘了带护照。',choices:['Passport','Ticket','Medicine'],answer:'Passport',explanation:'护照 means passport.'},{section:'Reading',prompt:'Choose the sentence showing a completed action.',choices:['我已经做完作业了。','我明天做作业。','我正在想作业。'],answer:'我已经做完作业了。',explanation:'已经…了 marks completion.'},{section:'Writing',prompt:'Complete: 除了中文___，我还会说英语。',answer:'以外',explanation:'除了…以外 commonly pairs with 还.'}],
  4:[{section:'Listening',prompt:'Why should the listener leave early?',audio:'路上可能堵车，你最好早点儿出发。',choices:['Traffic may be heavy','The train is cancelled','The shop closes'],answer:'Traffic may be heavy',explanation:'可能堵车 means traffic may be congested.'},{section:'Reading',prompt:'“不得不改变计划” means…',choices:['Have no choice but to change the plan','Refuse to make a plan','Finish the plan early'],answer:'Have no choice but to change the plan',explanation:'不得不 expresses necessity without a real alternative.'},{section:'Writing',prompt:'Complete: 无论多忙，他___坚持锻炼。',answer:'都',explanation:'无论…都… means no matter…still….'}],
  5:[{section:'Listening',prompt:'What does the team need to improve?',audio:'用户反馈说明我们需要简化注册流程。',choices:['The registration flow','The payment price','The office location'],answer:'The registration flow',explanation:'简化注册流程 means simplify the registration flow.'},{section:'Reading',prompt:'“从长远来看” introduces…',choices:['A long-term perspective','A direct quotation','A past mistake'],answer:'A long-term perspective',explanation:'从长远来看 means viewed over the long term.'},{section:'Writing',prompt:'Complete: 只有充分测试，___能稳定上线。',answer:'才',explanation:'只有…才… marks a necessary condition.'}],
  6:[{section:'Listening',prompt:'What risk is emphasized?',audio:'过度依赖单一供应商会削弱系统的韧性。',choices:['Dependence on one supplier','High employee turnover','A short meeting'],answer:'Dependence on one supplier',explanation:'过度依赖单一供应商 is over-reliance on one supplier.'},{section:'Reading',prompt:'“这一现象并非偶然” means the phenomenon is…',choices:['Not accidental','Impossible to observe','Already resolved'],answer:'Not accidental',explanation:'并非偶然 explicitly rejects coincidence.'},{section:'Writing',prompt:'Complete: 与其追求速度，___保证结果可靠。',answer:'不如',explanation:'与其…不如… contrasts two choices and prefers the latter.'}]
};

type ExamAnswer={correct:boolean;section:ExamQuestion['section'];prompt:string;answer:string;expected:string;explanation:string};

export function HskMockExam({level,speak,onFinish}:{level:number;speak:(text:string)=>void;onFinish:(score:number,total:number,weak:string[])=>void}){
  const questions=useMemo(()=>[...BANK[level],...EXTENDED_BANK[level]], [level]);const duration=questions.length*3*60;const [index,setIndex]=useState(0);const [answer,setAnswer]=useState('');const [answers,setAnswers]=useState<ExamAnswer[]>([]);const [seconds,setSeconds]=useState(duration);const [done,setDone]=useState(false);const question=questions[index];
  useEffect(()=>{if(done)return;const timer=window.setInterval(()=>setSeconds(value=>{if(value<=1){window.clearInterval(timer);setDone(true);return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[done]);
  const score=answers.filter(item=>item.correct).length;const weak=Object.entries(answers.reduce<Record<string,{right:number;total:number}>>((map,item)=>{map[item.section]??={right:0,total:0};map[item.section].total++;if(item.correct)map[item.section].right++;return map},{})).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total).map(item=>item[0]);
  function submit(){if(!answer.trim())return;const next=[...answers,{correct:answer.trim().toLowerCase()===question.answer.toLowerCase(),section:question.section,prompt:question.prompt,answer:answer.trim(),expected:question.answer,explanation:question.explanation}];setAnswers(next);setAnswer('');if(index===questions.length-1){const ranked=Object.entries(next.reduce<Record<string,{right:number;total:number}>>((map,item)=>{map[item.section]??={right:0,total:0};map[item.section].total++;if(item.correct)map[item.section].right++;return map},{})).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total).map(item=>item[0]);setDone(true);onFinish(next.filter(item=>item.correct).length,questions.length,ranked)}else setIndex(index+1)}
  if(done)return <section className="learning-panel advanced-lab"><p className="eyebrow">HSK MOCK EXAM · RESULT</p><h2>{score}/{questions.length} correct</h2><div className="exam-analysis">{['Listening','Reading','Writing'].map(section=>{const set=answers.filter(item=>item.section===section);const pct=Math.round(set.filter(item=>item.correct).length/Math.max(1,set.length)*100);return <article key={section}><strong>{section}</strong><b>{pct}%</b><i><em style={{width:`${pct}%`}}/></i></article>})}</div><p>Recommended next step: strengthen <b>{weak[0]??'mixed skills'}</b>, then repeat a timed set after spaced review.</p>{answers.some(item=>!item.correct)&&<div className="exam-review"><h3>Review missed questions</h3>{answers.filter(item=>!item.correct).map((item,itemIndex)=><article key={`${item.prompt}-${itemIndex}`}><small>{item.section}</small><strong>{item.prompt}</strong><p>Your answer: <b>{item.answer}</b> · Correct: <b>{item.expected}</b></p><span>{item.explanation}</span></article>)}</div>}<button onClick={()=>{setIndex(0);setAnswer('');setAnswers([]);setSeconds(duration);setDone(false)}}>Retake timed exam →</button></section>;
  return <section className="learning-panel advanced-lab"><header><div><p className="eyebrow">TIMED HSK {level} MOCK · {question.section.toUpperCase()}</p><h2>Full-skill exam simulator</h2></div><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong></header><div className="exam-progress"><i style={{width:`${index/questions.length*100}%`}}/></div><article className="exam-question"><small>QUESTION {index+1} OF {questions.length}</small><h3>{question.prompt}</h3>{question.audio&&<button onClick={()=>speak(question.audio!)}>▶ Play listening clue</button>}{question.choices?<div>{question.choices.map(choice=><button className={answer===choice?'active':''} onClick={()=>setAnswer(choice)} key={choice}>{choice}</button>)}</div>:<input value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="Type your answer…"/>}<button className="primary" disabled={!answer.trim()} onClick={submit}>Lock answer →</button></article></section>
}

export function AdaptiveStudyPlanner({hsk,onStart}:{hsk:number;onStart:(focus:string)=>void}){
  const [evidence]=useState<{mistakes:{correction:string;errorCount?:number;mastery?:number}[];events:{skill:string;correct:boolean;createdAt?:string}[]}>(()=>{if(typeof window==='undefined')return{mistakes:[],events:[]};try{const saved=JSON.parse(localStorage.getItem('long-learning-v2')??'{}');return{mistakes:Array.isArray(saved.mistakes)?saved.mistakes:[],events:Array.isArray(saved.events)?saved.events:[]}}catch{return{mistakes:[],events:[]}}});
  const {mistakes,events}=evidence;const skills=['Vocabulary','Listening','Reading','Grammar','Hanzi','Speaking'];const metrics=skills.map(skill=>{const set=events.filter(event=>event.skill===skill);const accuracy=set.length?set.filter(event=>event.correct).length/set.length:0;return{skill,accuracy,count:set.length,priority:(1-accuracy)*60+Math.max(0,12-set.length)*3}}).sort((a,b)=>b.priority-a.priority);const due=[...mistakes].sort((a,b)=>(b.errorCount??1)-(a.errorCount??1)||(a.mastery??0)-(b.mastery??0)).slice(0,5);
  return <section className="learning-panel adaptive-planner"><p className="eyebrow">ADAPTIVE ENGINE · NEXT BEST ACTION</p><h2>A session built from your evidence</h2><p>The queue weighs errors, response evidence, mastery, HSK {hsk}, and under-practiced skills. It deliberately avoids repeating only easy questions.</p><div className="adaptive-focus-grid">{metrics.slice(0,3).map((item,index)=><article key={item.skill}><span>{index+1}</span><p><strong>{item.skill}</strong><small>{item.count} attempts · {Math.round(item.accuracy*100)}% accuracy</small></p><b>{Math.round(item.priority)} priority</b></article>)}</div><div className="adaptive-queue"><strong>Next session mix</strong><span>40% {metrics[0].skill}</span><span>30% frequent mistakes</span><span>20% spaced recall</span><span>10% stretch HSK {Math.min(6,hsk+1)}</span></div>{due.length>0&&<p className="adaptive-mistakes"><b>First recovery targets:</b> {due.map(item=>item.correction).join(' · ')}</p>}<button onClick={()=>onStart(metrics[0].skill)}>Start adaptive {metrics[0].skill.toLowerCase()} session →</button></section>
}

export function OfflineLibrary(){
  const shell=['/','/offline.html','/manifest.webmanifest','/favicon.svg'];
  const packs=[
    {id:'hsk1',mark:'一',title:'HSK 1 Foundations',copy:'Core lessons, dictionary and beginner review',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'hsk2',mark:'二',title:'HSK 2 Everyday Chinese',copy:'Daily situations, grammar and review',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'hsk3',mark:'三',title:'HSK 3 Independent Learner',copy:'Longer reading, listening and review',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'hsk4',mark:'四',title:'HSK 4 Upper & Lower',copy:'Intermediate course, stories and review',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'hsk5',mark:'五',title:'HSK 5 Advanced',copy:'Advanced vocabulary and reading tools',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'hsk6',mark:'六',title:'HSK 6 Mastery',copy:'High-level vocabulary and exam practice',assets:[...shell,'/app/hsk-vocabulary.json']},
    {id:'stories',mark:'故',title:'Stories & China Scenes',copy:'Story reader and selected visual context',assets:[...shell,'/landmarks/the-bund-shanghai.jpg','/landmarks/fuzimiao-nanjing.jpg','/landmarks/west-lake-hangzhou.jpg','/scenes/airport-terminal.jpg','/scenes/metro-platform.jpg']},
    {id:'professional',mark:'专',title:'Professional Chinese',copy:'Major-specific vocabulary and scenarios',assets:[...shell,'/app/hsk-vocabulary.json']}
  ] as const;
  const [saved,setSaved]=useState<string[]>([]);const [busy,setBusy]=useState('');const [usage,setUsage]=useState('Calculating…');const [online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener('online',update);addEventListener('offline',update);caches.keys().then(keys=>setSaved(keys.filter(key=>key.startsWith('long-pack-')).map(key=>key.replace('long-pack-','')))).catch(()=>undefined);navigator.storage?.estimate().then(result=>setUsage(`${((result.usage??0)/1048576).toFixed(1)} MB used`));return()=>{removeEventListener('online',update);removeEventListener('offline',update)}},[]);
  async function toggle(pack:typeof packs[number]){if(!('caches'in window))return;setBusy(pack.id);try{const cacheName=`long-pack-${pack.id}`;if(saved.includes(pack.id)){await caches.delete(cacheName);setSaved(items=>items.filter(item=>item!==pack.id))}else{const cache=await caches.open(cacheName);for(const asset of pack.assets){try{await cache.add(asset)}catch{/* keep the rest of the pack usable when one optional route is unavailable */}}setSaved(items=>Array.from(new Set([...items,pack.id])))}const estimate=await navigator.storage?.estimate();if(estimate)setUsage(`${((estimate.usage??0)/1048576).toFixed(1)} MB used`)}finally{setBusy('')}}
  return <section className="learning-panel offline-manager"><header><div><p className="eyebrow">DOWNLOADED LESSONS · 离线内容</p><h2>Manage learning without internet</h2><p>Choose an exact HSK, story, or professional pack. Each pack has its own cache, so removing one genuinely releases its stored files.</p></div><span className={online?'online':'offline'}>{online?'● Online · sync ready':'○ Offline · progress queued'}</span></header><div className="offline-storage"><strong>{saved.length} of {packs.length} packs downloaded</strong><span>{usage}</span><i><em style={{width:`${Math.min(100,saved.length/packs.length*100)}%`}}/></i></div><div className="offline-pack-grid">{packs.map(pack=>{const ready=saved.includes(pack.id);return <article key={pack.id}><span>{pack.mark}</span><p><strong>{pack.title}</strong><small>{pack.assets.length} cached resources · {pack.copy}</small></p><button disabled={busy===pack.id} onClick={()=>toggle(pack)}>{busy===pack.id?'Working…':ready?'Remove':'Download'}</button><b>{ready?'✓ Ready offline':'Cloud only'}</b></article>})}</div><footer><b>Pending sync:</b> {online?'All device changes can synchronize now.':'Your XP, reviews, mistakes, and saved words remain safely queued on this device.'}</footer></section>
}
