'use client';

import { useEffect, useMemo, useState } from 'react';

type ExamQuestion={section:'Listening'|'Reading'|'Writing';prompt:string;audio?:string;choices?:string[];answer:string;explanation:string};
const BANK:Record<number,ExamQuestion[]>={
  1:[{section:'Listening',prompt:'What greeting do you hear?',audio:'你好',choices:['Hello','Goodbye','Thank you'],answer:'Hello',explanation:'你好 is the standard greeting.'},{section:'Reading',prompt:'Choose “I am a student.”',choices:['我是学生。','我喝学生。','学生很好吃。'],answer:'我是学生。',explanation:'我是学生 uses 是 to identify the subject.'},{section:'Writing',prompt:'Type the Hanzi for “China”.',answer:'中国',explanation:'China is written 中国.'}],
  2:[{section:'Listening',prompt:'Where does the speaker want to go?',audio:'我想去火车站。',choices:['Train station','Hospital','Restaurant'],answer:'Train station',explanation:'火车站 means train station.'},{section:'Reading',prompt:'Choose the natural sequence.',choices:['我先吃饭，然后学习。','我然后先学习吃饭。','先我然后。'],answer:'我先吃饭，然后学习。',explanation:'先…然后… shows ordered actions.'},{section:'Writing',prompt:'Type the missing word: 今天___昨天冷。',answer:'比',explanation:'A 比 B + adjective makes a comparison.'}],
  3:[{section:'Listening',prompt:'Why was the match cancelled?',audio:'因为下雨，所以比赛取消了。',choices:['Rain','Traffic','Illness'],answer:'Rain',explanation:'因为下雨 gives the reason.'},{section:'Reading',prompt:'What does “越来越方便” mean?',choices:['More and more convenient','Less expensive','Already finished'],answer:'More and more convenient',explanation:'越来越 marks a continuing change.'},{section:'Writing',prompt:'Complete: 虽然很累，___他还在工作。',answer:'但是',explanation:'虽然 commonly pairs with 但是.'}],
  4:[{section:'Listening',prompt:'What is being recommended?',audio:'我建议你提前预约。',choices:['Reserve in advance','Cancel today','Pay cash'],answer:'Reserve in advance',explanation:'提前预约 means reserve in advance.'},{section:'Reading',prompt:'“值得考虑” means…',choices:['Worth considering','Impossible to finish','Already rejected'],answer:'Worth considering',explanation:'值得 means worthy of.'},{section:'Writing',prompt:'Complete: 只要坚持，___会进步。',answer:'就',explanation:'只要…就… expresses a sufficient condition.'}],
  5:[{section:'Listening',prompt:'What concern is mentioned?',audio:'这个方案可能会增加技术债务。',choices:['Technical debt','Tuition','Weather'],answer:'Technical debt',explanation:'技术债务 means technical debt.'},{section:'Reading',prompt:'“结果仍有待验证” means…',choices:['Results still need verification','Results are final','Experiment was cancelled'],answer:'Results still need verification',explanation:'有待 means remains to be done.'},{section:'Writing',prompt:'Complete: 与其等待，___马上行动。',answer:'不如',explanation:'与其…不如… expresses preference.'}],
  6:[{section:'Listening',prompt:'What is the speaker evaluating?',audio:'我们必须权衡效率与隐私之间的关系。',choices:['Efficiency and privacy','Price and color','Travel and weather'],answer:'Efficiency and privacy',explanation:'权衡 means weigh or balance.'},{section:'Reading',prompt:'“该结论未免过于武断” suggests the conclusion is…',choices:['Too arbitrary','Well supported','Easy to understand'],answer:'Too arbitrary',explanation:'未免过于武断 criticizes an overly arbitrary claim.'},{section:'Writing',prompt:'Complete: 即使遇到困难，___不能放弃。',answer:'也',explanation:'即使…也… means even if…still….'}]
};

export function HskMockExam({level,speak,onFinish}:{level:number;speak:(text:string)=>void;onFinish:(score:number,total:number,weak:string[])=>void}){
  const questions=useMemo(()=>[...BANK[level],...BANK[level]], [level]);const [index,setIndex]=useState(0);const [answer,setAnswer]=useState('');const [answers,setAnswers]=useState<{correct:boolean;section:string}[]>([]);const [seconds,setSeconds]=useState(15*60);const [done,setDone]=useState(false);const question=questions[index];
  useEffect(()=>{if(done)return;const timer=window.setInterval(()=>setSeconds(value=>{if(value<=1){window.clearInterval(timer);setDone(true);return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[done]);
  const score=answers.filter(item=>item.correct).length;const weak=Object.entries(answers.reduce<Record<string,{right:number;total:number}>>((map,item)=>{map[item.section]??={right:0,total:0};map[item.section].total++;if(item.correct)map[item.section].right++;return map},{})).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total).map(item=>item[0]);
  function submit(){if(!answer.trim())return;const next=[...answers,{correct:answer.trim().toLowerCase()===question.answer.toLowerCase(),section:question.section}];setAnswers(next);setAnswer('');if(index===questions.length-1){setDone(true);onFinish(next.filter(item=>item.correct).length,questions.length,weak)}else setIndex(index+1)}
  if(done)return <section className="learning-panel advanced-lab"><p className="eyebrow">HSK MOCK EXAM · RESULT</p><h2>{score}/{questions.length} correct</h2><div className="exam-analysis">{['Listening','Reading','Writing'].map(section=>{const set=answers.filter(item=>item.section===section);const pct=Math.round(set.filter(item=>item.correct).length/Math.max(1,set.length)*100);return <article key={section}><strong>{section}</strong><b>{pct}%</b><i><em style={{width:`${pct}%`}}/></i></article>})}</div><p>Recommended next step: strengthen <b>{weak[0]??'mixed skills'}</b>, then repeat a timed set after spaced review.</p><button onClick={()=>{setIndex(0);setAnswer('');setAnswers([]);setSeconds(15*60);setDone(false)}}>Retake timed exam →</button></section>;
  return <section className="learning-panel advanced-lab"><header><div><p className="eyebrow">TIMED HSK {level} MOCK · {question.section.toUpperCase()}</p><h2>Full-skill exam simulator</h2></div><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong></header><div className="exam-progress"><i style={{width:`${index/questions.length*100}%`}}/></div><article className="exam-question"><small>QUESTION {index+1} OF {questions.length}</small><h3>{question.prompt}</h3>{question.audio&&<button onClick={()=>speak(question.audio!)}>▶ Play listening clue</button>}{question.choices?<div>{question.choices.map(choice=><button className={answer===choice?'active':''} onClick={()=>setAnswer(choice)} key={choice}>{choice}</button>)}</div>:<input value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="Type your answer…"/>}<button className="primary" disabled={!answer.trim()} onClick={submit}>Lock answer →</button></article></section>
}

export function AdaptiveStudyPlanner({hsk,onStart}:{hsk:number;onStart:(focus:string)=>void}){
  const [evidence]=useState<{mistakes:{correction:string;errorCount?:number;mastery?:number}[];events:{skill:string;correct:boolean;createdAt?:string}[]}>(()=>{if(typeof window==='undefined')return{mistakes:[],events:[]};try{const saved=JSON.parse(localStorage.getItem('long-learning-v2')??'{}');return{mistakes:Array.isArray(saved.mistakes)?saved.mistakes:[],events:Array.isArray(saved.events)?saved.events:[]}}catch{return{mistakes:[],events:[]}}});
  const {mistakes,events}=evidence;const skills=['Vocabulary','Listening','Reading','Grammar','Hanzi','Speaking'];const metrics=skills.map(skill=>{const set=events.filter(event=>event.skill===skill);const accuracy=set.length?set.filter(event=>event.correct).length/set.length:0;return{skill,accuracy,count:set.length,priority:(1-accuracy)*60+Math.max(0,12-set.length)*3}}).sort((a,b)=>b.priority-a.priority);const due=[...mistakes].sort((a,b)=>(b.errorCount??1)-(a.errorCount??1)||(a.mastery??0)-(b.mastery??0)).slice(0,5);
  return <section className="learning-panel adaptive-planner"><p className="eyebrow">ADAPTIVE ENGINE · NEXT BEST ACTION</p><h2>A session built from your evidence</h2><p>The queue weighs errors, response evidence, mastery, HSK {hsk}, and under-practiced skills. It deliberately avoids repeating only easy questions.</p><div className="adaptive-focus-grid">{metrics.slice(0,3).map((item,index)=><article key={item.skill}><span>{index+1}</span><p><strong>{item.skill}</strong><small>{item.count} attempts · {Math.round(item.accuracy*100)}% accuracy</small></p><b>{Math.round(item.priority)} priority</b></article>)}</div><div className="adaptive-queue"><strong>Next session mix</strong><span>40% {metrics[0].skill}</span><span>30% frequent mistakes</span><span>20% spaced recall</span><span>10% stretch HSK {Math.min(6,hsk+1)}</span></div>{due.length>0&&<p className="adaptive-mistakes"><b>First recovery targets:</b> {due.map(item=>item.correction).join(' · ')}</p>}<button onClick={()=>onStart(metrics[0].skill)}>Start adaptive {metrics[0].skill.toLowerCase()} session →</button></section>
}

export function OfflineLibrary(){
  const packs=[{id:'hsk1-2',title:'HSK 1–2 Essentials',size:'≈ 4 MB',assets:['/','/offline.html','/app/hsk-vocabulary.json']},{id:'hsk3-4',title:'HSK 3–4 Course + stories',size:'≈ 6 MB',assets:['/','/offline.html','/app/hsk-vocabulary.json']},{id:'hsk5-6',title:'HSK 5–6 Advanced',size:'≈ 7 MB',assets:['/','/offline.html','/app/hsk-vocabulary.json']},{id:'professional',title:'Professional Chinese',size:'≈ 3 MB',assets:['/','/offline.html']}] as const;
  const [saved,setSaved]=useState<string[]>([]);const [busy,setBusy]=useState('');const [usage,setUsage]=useState('Calculating…');const [online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener('online',update);addEventListener('offline',update);caches.open('long-content-v2').then(async cache=>{const keys=await cache.keys();setSaved(keys.map(item=>new URL(item.url).searchParams.get('pack')).filter(Boolean) as string[])}).catch(()=>undefined);navigator.storage?.estimate().then(result=>setUsage(`${((result.usage??0)/1048576).toFixed(1)} MB used`));return()=>{removeEventListener('online',update);removeEventListener('offline',update)}},[]);
  async function toggle(pack:typeof packs[number]){if(!('caches'in window))return;setBusy(pack.id);try{const cache=await caches.open('long-content-v2');const marker=`/?pack=${pack.id}`;if(saved.includes(pack.id)){await cache.delete(marker);setSaved(items=>items.filter(item=>item!==pack.id))}else{for(const asset of pack.assets){try{await cache.add(asset)}catch{/* one optional asset may be generated inside the app bundle */}}const shell=await cache.match('/');if(shell)await cache.put(marker,shell.clone());setSaved(items=>[...items,pack.id])}const estimate=await navigator.storage?.estimate();if(estimate)setUsage(`${((estimate.usage??0)/1048576).toFixed(1)} MB used`)}finally{setBusy('')}}
  return <section className="learning-panel offline-manager"><header><div><p className="eyebrow">DOWNLOADED LESSONS · 离线内容</p><h2>Manage learning without internet</h2><p>Choose exact HSK or professional packs. The app keeps progress locally and uploads pending changes after reconnection.</p></div><span className={online?'online':'offline'}>{online?'● Online · sync ready':'○ Offline · progress queued'}</span></header><div className="offline-storage"><strong>{saved.length} packs downloaded</strong><span>{usage}</span><i><em style={{width:`${Math.min(100,saved.length/4*100)}%`}}/></i></div><div className="offline-pack-grid">{packs.map((pack,index)=>{const ready=saved.includes(pack.id);return <article key={pack.id}><span>{['基','中','高','专'][index]}</span><p><strong>{pack.title}</strong><small>{pack.size} · lessons, dictionary and app shell</small></p><button disabled={busy===pack.id} onClick={()=>toggle(pack)}>{busy===pack.id?'Working…':ready?'Remove':'Download'}</button><b>{ready?'✓ Ready offline':'Cloud only'}</b></article>})}</div><footer><b>Pending sync:</b> {online?'All device changes can synchronize now.':'Your XP, reviews, mistakes, and saved words remain safely queued on this device.'}</footer></section>
}
