import licensedAdventureScenes from './adventure-scenes.json' with { type: 'json' };

export type ChinaWord = { hanzi:string; pinyin:string; english:string };
export type ChinaPlace = { id:string; name:string; pinyin:string; english:string; city:string; image:string; fact:string; credit:string; source:string; words:ChinaWord[] };
export type ChapterScene = { image:string; label:string; chinese:string; prompt:string; credit:string; source?:string };

const commons=(file:string)=>`https://commons.wikimedia.org/wiki/File:${file}`;

export const chinaPlaces:ChinaPlace[]=[
  {id:'fuzimiao',name:'夫子庙',pinyin:'Fūzǐmiào',english:'Confucius Temple',city:'南京 · Nanjing',image:'/landmarks/fuzimiao-nanjing.jpg',fact:'Follow the Qinhuai River into Nanjing’s lantern-lit historic quarter.',credit:'Kenneth Lu · CC BY 2.0',source:commons('Nanjing_FuziMiao_DaZhaobi3.jpg'),words:[{hanzi:'门票',pinyin:'ménpiào',english:'entrance ticket'},{hanzi:'夜景',pinyin:'yèjǐng',english:'night view'},{hanzi:'小吃',pinyin:'xiǎochī',english:'snack'},{hanzi:'河边',pinyin:'hébiān',english:'riverside'}]},
  {id:'bund',name:'外滩',pinyin:'Wàitān',english:'The Bund',city:'上海 · Shanghai',image:'/landmarks/the-bund-shanghai.jpg',fact:'See Shanghai’s historic façades and futuristic Pudong skyline meet across the Huangpu River.',credit:'CC0 · Wikimedia Commons',source:commons('Shanghai_skyline_from_the_bund.jpg'),words:[{hanzi:'江景',pinyin:'jiāngjǐng',english:'river view'},{hanzi:'观景台',pinyin:'guānjǐngtái',english:'observation deck'},{hanzi:'轮渡',pinyin:'lúndù',english:'ferry'},{hanzi:'拍照',pinyin:'pāizhào',english:'take a photo'},{hanzi:'售票处',pinyin:'shòupiàochù',english:'ticket office'}]},
  {id:'mutianyu',name:'慕田峪长城',pinyin:'Mùtiányù Chángchéng',english:'Mutianyu Great Wall',city:'北京 · Beijing',image:'/landmarks/mutianyu-great-wall.jpg',fact:'Walk a beautifully restored, mountain-framed section of the Great Wall.',credit:'J. Samuel Burner · CC BY 2.0',source:commons('Great_Wall_at_Mutianyu.jpg'),words:[{hanzi:'缆车',pinyin:'lǎnchē',english:'cable car'},{hanzi:'入口',pinyin:'rùkǒu',english:'entrance'},{hanzi:'台阶',pinyin:'táijiē',english:'steps'},{hanzi:'山顶',pinyin:'shāndǐng',english:'mountaintop'}]},
  {id:'west-lake',name:'西湖',pinyin:'Xīhú',english:'West Lake',city:'杭州 · Hangzhou',image:'/landmarks/west-lake-hangzhou.jpg',fact:'Learn why poets have celebrated Hangzhou’s lake, bridges, and sunsets for centuries.',credit:'Yinweichen · Creative Commons',source:commons('Sunset_with_Willow_and_Boats_on_West_Lake.jpg'),words:[{hanzi:'游船',pinyin:'yóuchuán',english:'tour boat'},{hanzi:'断桥',pinyin:'Duànqiáo',english:'Broken Bridge'},{hanzi:'湖边',pinyin:'húbiān',english:'lakeside'},{hanzi:'日落',pinyin:'rìluò',english:'sunset'}]},
  {id:'terracotta',name:'兵马俑',pinyin:'Bīngmǎyǒng',english:'Terracotta Army',city:'西安 · Xi’an',image:'/landmarks/terracotta-xian.jpg',fact:'Enter the vast archaeological halls protecting Qin-era warriors and chariots.',credit:'David Castor · Public domain',source:commons('Terrakottaarmén-1.jpg'),words:[{hanzi:'博物馆',pinyin:'bówùguǎn',english:'museum'},{hanzi:'展厅',pinyin:'zhǎntīng',english:'exhibition hall'},{hanzi:'讲解员',pinyin:'jiǎngjiěyuán',english:'guide'},{hanzi:'预约',pinyin:'yùyuē',english:'reservation'}]},
  {id:'panda',name:'熊猫基地',pinyin:'Xióngmāo Jīdì',english:'Panda Base',city:'成都 · Chengdu',image:'/landmarks/chengdu-panda.jpg',fact:'Visit early to see giant pandas eating bamboo and exploring their habitats.',credit:'Mikael Häggström · Public domain',source:commons('Giant_Panda_at_Chengdu_Panda_Base.jpg'),words:[{hanzi:'熊猫',pinyin:'xióngmāo',english:'panda'},{hanzi:'竹子',pinyin:'zhúzi',english:'bamboo'},{hanzi:'园区',pinyin:'yuánqū',english:'park area'},{hanzi:'排队',pinyin:'páiduì',english:'queue'}]},
  {id:'lijiang',name:'漓江',pinyin:'Líjiāng',english:'Li River',city:'桂林 · Guilin',image:'/landmarks/li-river-guilin.jpg',fact:'Cruise between karst peaks, riverside villages, and bamboo rafts.',credit:'ToastyKen · Creative Commons',source:commons('LiRiver.jpg'),words:[{hanzi:'竹筏',pinyin:'zhúfá',english:'bamboo raft'},{hanzi:'码头',pinyin:'mǎtóu',english:'pier'},{hanzi:'山水',pinyin:'shānshuǐ',english:'mountain-and-water scenery'},{hanzi:'船票',pinyin:'chuánpiào',english:'boat ticket'}]},
  {id:'hongya',name:'洪崖洞',pinyin:'Hóngyádòng',english:'Hongya Cave',city:'重庆 · Chongqing',image:'/landmarks/hongya-chongqing.jpg',fact:'Explore a cliffside complex of glowing shops, food stalls, and river views.',credit:'Xiquinho Silva · CC BY 2.0',source:commons('Hongya_Cave_20180520.jpg'),words:[{hanzi:'夜市',pinyin:'yèshì',english:'night market'},{hanzi:'楼层',pinyin:'lóucéng',english:'floor/storey'},{hanzi:'电梯',pinyin:'diàntī',english:'elevator'},{hanzi:'火锅',pinyin:'huǒguō',english:'hotpot'}]},
  {id:'pingjiang',name:'平江路',pinyin:'Píngjiāng Lù',english:'Pingjiang Road',city:'苏州 · Suzhou',image:'/landmarks/pingjiang-suzhou.jpg',fact:'Walk beside old canals, stone bridges, teahouses, and whitewashed homes.',credit:'Windmemories · CC BY-SA 4.0',source:commons('2017-04-16_Pingjianglu,_Suzhou.jpg'),words:[{hanzi:'古街',pinyin:'gǔjiē',english:'historic street'},{hanzi:'小桥',pinyin:'xiǎoqiáo',english:'small bridge'},{hanzi:'茶馆',pinyin:'cháguǎn',english:'teahouse'},{hanzi:'运河',pinyin:'yùnhé',english:'canal'}]},
  {id:'canton',name:'广州塔',pinyin:'Guǎngzhōu Tǎ',english:'Canton Tower',city:'广州 · Guangzhou',image:'/landmarks/canton-tower.jpg',fact:'Rise above the Pearl River for a wide city view from one of China’s tallest towers.',credit:'Tim Wu · CC BY-SA 4.0',source:commons('Canton_Tower_20220626.jpg'),words:[{hanzi:'观光',pinyin:'guānguāng',english:'sightseeing'},{hanzi:'电梯',pinyin:'diàntī',english:'elevator'},{hanzi:'顶层',pinyin:'dǐngcéng',english:'top floor'},{hanzi:'珠江',pinyin:'Zhūjiāng',english:'Pearl River'}]},
  {id:'temple-heaven',name:'天坛',pinyin:'Tiāntán',english:'Temple of Heaven',city:'北京 · Beijing',image:'/landmarks/temple-heaven.jpg',fact:'Discover imperial architecture and join locals practicing in the surrounding park.',credit:'Wikimedia Commons',source:commons('Temple_of_Heaven,_Beijing.jpg'),words:[{hanzi:'公园',pinyin:'gōngyuán',english:'park'},{hanzi:'祈年殿',pinyin:'Qínián Diàn',english:'Hall of Prayer'},{hanzi:'南门',pinyin:'nánmén',english:'south gate'},{hanzi:'开放时间',pinyin:'kāifàng shíjiān',english:'opening hours'}]},
  {id:'zhangjiajie',name:'张家界',pinyin:'Zhāngjiājiè',english:'National Forest Park',city:'湖南 · Hunan',image:'/landmarks/zhangjiajie.jpg',fact:'Travel among misty sandstone pillars, glass lifts, and mountain trails.',credit:'Wikimedia Commons',source:commons('Zhangjiajie_National_Forest_Park.jpg'),words:[{hanzi:'索道',pinyin:'suǒdào',english:'cableway'},{hanzi:'步道',pinyin:'bùdào',english:'walking trail'},{hanzi:'风景区',pinyin:'fēngjǐngqū',english:'scenic area'},{hanzi:'地图',pinyin:'dìtú',english:'map'}]},
  {id:'harbin',name:'冰雪大世界',pinyin:'Bīngxuě Dà Shìjiè',english:'Ice and Snow World',city:'哈尔滨 · Harbin',image:'/landmarks/harbin-ice.jpg',fact:'See monumental illuminated ice architecture during Harbin’s winter festival.',credit:'Wikimedia Commons',source:commons('Harbin_Ice_Festival.jpg'),words:[{hanzi:'冰雕',pinyin:'bīngdiāo',english:'ice sculpture'},{hanzi:'保暖',pinyin:'bǎonuǎn',english:'keep warm'},{hanzi:'手套',pinyin:'shǒutào',english:'gloves'},{hanzi:'零下',pinyin:'língxià',english:'below zero'}]},
  {id:'shenzhen',name:'深圳湾',pinyin:'Shēnzhèn Wān',english:'Shenzhen Bay',city:'深圳 · Shenzhen',image:'/landmarks/shenzhen-bay.jpg',fact:'Cycle through waterfront parks with views of a fast-changing technology city.',credit:'Windmemories · CC BY-SA 4.0',source:commons('20201112_The_skyline_at_Shenzhen_Bay.jpg'),words:[{hanzi:'海湾',pinyin:'hǎiwān',english:'bay'},{hanzi:'自行车道',pinyin:'zìxíngchēdào',english:'bike lane'},{hanzi:'科技园',pinyin:'kējìyuán',english:'technology park'},{hanzi:'天际线',pinyin:'tiānjìxiàn',english:'skyline'}]},
];

const A='/scenes/airport-terminal.jpg',B='/scenes/airport-arrivals.jpg',M='/scenes/metro-platform.jpg',T='/scenes/high-speed-train.jpg',D='/scenes/train-display.jpg';
const L=(file:string)=>`/landmarks/${file}`;
export const chapterScenes:Record<string,ChapterScene[]>={
  arrival:[{image:A,label:'Terminal 3',chinese:'航站楼',prompt:'Find immigration and the arrival hall.',credit:'Beijing Capital Airport · CC'},{image:B,label:'Arrival hall',chinese:'到达大厅',prompt:'Collect baggage and follow the exit signs.',credit:'Beijing Capital Airport · CC'},{image:M,label:'Airport metro',chinese:'机场地铁',prompt:'Buy a metro ticket into the city.',credit:'Shanghai Metro · CC BY-SA'},{image:T,label:'High-speed connection',chinese:'高铁换乘',prompt:'Connect to another city by high-speed rail.',credit:'CRH · CC BY-SA'},{image:L('the-bund-shanghai.jpg'),label:'First city view',chinese:'城市初印象',prompt:'Use your first directions in a real city.',credit:'Wikimedia Commons'}],
  hotel:[{image:L('canton-tower.jpg'),label:'City hotel district',chinese:'酒店区',prompt:'Find your hotel among city landmarks.',credit:'Tim Wu · CC BY-SA'},{image:A,label:'Transfer desk',chinese:'服务台',prompt:'Ask staff to confirm the hotel address.',credit:'Wikimedia Commons'},{image:L('fuzimiao-nanjing.jpg'),label:'Historic stay',chinese:'老城区住宿',prompt:'Check in near a historic neighborhood.',credit:'Kenneth Lu · CC BY'},{image:L('shenzhen-bay.jpg'),label:'Modern skyline',chinese:'城市景观房',prompt:'Ask whether the room has a city view.',credit:'Windmemories · CC BY-SA'},{image:L('west-lake-hangzhou.jpg'),label:'Lakeside hotel',chinese:'湖景酒店',prompt:'Request a quiet room near the lake.',credit:'Creative Commons'}],
  restaurant:[{image:L('hongya-chongqing.jpg'),label:'Hotpot district',chinese:'火锅街',prompt:'Reserve a table and choose your spice level.',credit:'Xiquinho Silva · CC BY'},{image:L('pingjiang-suzhou.jpg'),label:'Canal teahouse',chinese:'河边茶馆',prompt:'Order tea and a local snack.',credit:'Windmemories · CC BY-SA'},{image:L('fuzimiao-nanjing.jpg'),label:'Night food street',chinese:'小吃街',prompt:'Ask what the house specialty is.',credit:'Kenneth Lu · CC BY'},{image:L('the-bund-shanghai.jpg'),label:'Riverside dining',chinese:'江景餐厅',prompt:'Request a table by the window.',credit:'Wikimedia Commons'},{image:L('chengdu-panda.jpg'),label:'Chengdu flavors',chinese:'成都味道',prompt:'Ask for a dish that is not too spicy.',credit:'Public domain'}],
  transport:[{image:M,label:'Metro platform',chinese:'地铁站台',prompt:'Check the direction before boarding.',credit:'Shanghai Metro · CC BY-SA'},{image:D,label:'Train information',chinese:'车厢信息',prompt:'Read the train number and next station.',credit:'CRH · GFDL'},{image:T,label:'High-speed cabin',chinese:'高铁车厢',prompt:'Find your carriage and seat.',credit:'CRH · CC BY-SA'},{image:A,label:'Airport connection',chinese:'机场换乘',prompt:'Transfer between terminal and metro.',credit:'Wikimedia Commons'},{image:L('shenzhen-bay.jpg'),label:'Taxi arrival',chinese:'出租车下车点',prompt:'Tell the driver exactly where to stop.',credit:'Windmemories · CC BY-SA'}],
  shopping:[{image:L('pingjiang-suzhou.jpg'),label:'Local shops',chinese:'特色商店',prompt:'Ask the price and whether another size is available.',credit:'Windmemories · CC BY-SA'},{image:L('hongya-chongqing.jpg'),label:'Night market',chinese:'夜市购物',prompt:'Compare prices and pay by QR code.',credit:'Xiquinho Silva · CC BY'},{image:L('canton-tower.jpg'),label:'Souvenir counter',chinese:'纪念品店',prompt:'Choose a gift and ask for a bag.',credit:'Tim Wu · CC BY-SA'},{image:L('fuzimiao-nanjing.jpg'),label:'Craft street',chinese:'手工艺街',prompt:'Ask whether an item is handmade.',credit:'Kenneth Lu · CC BY'},{image:L('the-bund-shanghai.jpg'),label:'Department store',chinese:'百货商场',prompt:'Find the correct floor and cashier.',credit:'Wikimedia Commons'}],
  campus:[{image:L('temple-heaven.jpg'),label:'Morning campus',chinese:'校园早晨',prompt:'Ask where the lecture hall is.',credit:'Wikimedia Commons'},{image:L('shenzhen-bay.jpg'),label:'Technology campus',chinese:'科技园区',prompt:'Meet your project group near the lab.',credit:'Windmemories · CC BY-SA'},{image:T,label:'Study trip',chinese:'研学旅行',prompt:'Travel with classmates to another city.',credit:'CRH · CC BY-SA'},{image:L('west-lake-hangzhou.jpg'),label:'Campus lake',chinese:'校园湖边',prompt:'Invite a classmate to study together.',credit:'Creative Commons'},{image:L('terracotta-xian.jpg'),label:'Museum assignment',chinese:'博物馆作业',prompt:'Discuss a class field trip.',credit:'Public domain'}],
  health:[{image:A,label:'Airport clinic',chinese:'机场医务室',prompt:'Explain a symptom and ask for help.',credit:'Wikimedia Commons'},{image:L('west-lake-hangzhou.jpg'),label:'Morning exercise',chinese:'晨练',prompt:'Talk about sleep, walking, and wellbeing.',credit:'Creative Commons'},{image:L('temple-heaven.jpg'),label:'Community exercise',chinese:'社区锻炼',prompt:'Join locals exercising in the park.',credit:'Wikimedia Commons'},{image:L('shenzhen-bay.jpg'),label:'Waterfront run',chinese:'海边跑步',prompt:'Describe pain after exercise.',credit:'Windmemories · CC BY-SA'},{image:L('chengdu-panda.jpg'),label:'Rest and recovery',chinese:'休息恢复',prompt:'Ask where the nearest pharmacy is.',credit:'Public domain'}],
  social:[{image:L('the-bund-shanghai.jpg'),label:'Meet at the Bund',chinese:'外滩见面',prompt:'Share a location and arrival time.',credit:'Wikimedia Commons'},{image:L('west-lake-hangzhou.jpg'),label:'Weekend plan',chinese:'周末计划',prompt:'Invite friends to take a boat.',credit:'Creative Commons'},{image:L('hongya-chongqing.jpg'),label:'Night out',chinese:'晚上聚会',prompt:'Send the restaurant location in WeChat.',credit:'Xiquinho Silva · CC BY'},{image:L('chengdu-panda.jpg'),label:'Group visit',chinese:'一起参观',prompt:'Choose a meeting point and time.',credit:'Public domain'},{image:L('li-river-guilin.jpg'),label:'Travel chat',chinese:'旅行群聊',prompt:'Share photos and plan tomorrow.',credit:'Creative Commons'}],
  coffee:[{image:L('pingjiang-suzhou.jpg'),label:'Canal café',chinese:'河边咖啡馆',prompt:'Order a drink and choose a seat.',credit:'Windmemories · CC BY-SA'},{image:L('the-bund-shanghai.jpg'),label:'Skyline coffee',chinese:'景观咖啡',prompt:'Ask whether the window seat is free.',credit:'Wikimedia Commons'},{image:L('shenzhen-bay.jpg'),label:'Work café',chinese:'办公咖啡馆',prompt:'Ask for Wi-Fi and a power outlet.',credit:'Windmemories · CC BY-SA'},{image:L('fuzimiao-nanjing.jpg'),label:'Old-town café',chinese:'老城咖啡',prompt:'Order a seasonal specialty.',credit:'Kenneth Lu · CC BY'},{image:L('west-lake-hangzhou.jpg'),label:'Lakeside tea & coffee',chinese:'湖边饮品',prompt:'Choose between tea and coffee.',credit:'Creative Commons'}],
  sightseeing:[{image:L('terracotta-xian.jpg'),label:'Terracotta Army halls',chinese:'兵马俑展厅',prompt:'Show your ticket and find the correct exhibition hall.',credit:'Public domain'},{image:L('temple-heaven.jpg'),label:'Temple of Heaven',chinese:'天坛',prompt:'Check the opening time and enter through the correct gate.',credit:'Wikimedia Commons'},{image:L('fuzimiao-nanjing.jpg'),label:'Confucius Temple',chinese:'夫子庙',prompt:'Ask for an audio guide and visitor map.',credit:'Kenneth Lu · CC BY'},{image:L('canton-tower.jpg'),label:'Observation deck',chinese:'观景台',prompt:'Collect a timed ticket for the elevator.',credit:'Tim Wu · CC BY-SA'},{image:L('zhangjiajie.jpg'),label:'Scenic area entrance',chinese:'景区入口',prompt:'Confirm the route and last return time.',credit:'Wikimedia Commons'}],
  payments:[{image:L('shenzhen-bay.jpg'),label:'Digital city checkout',chinese:'移动支付',prompt:'Scan a QR code and confirm the amount.',credit:'Windmemories · CC BY-SA'},{image:L('hongya-chongqing.jpg'),label:'Night-market payment',chinese:'夜市付款',prompt:'Ask whether the stall accepts mobile payment.',credit:'Xiquinho Silva · CC BY'},{image:L('pingjiang-suzhou.jpg'),label:'Small-shop QR code',chinese:'商店二维码',prompt:'Scan the merchant code and show payment success.',credit:'Windmemories · CC BY-SA'},{image:L('canton-tower.jpg'),label:'Ticket counter',chinese:'售票柜台',prompt:'Request a digital receipt after paying.',credit:'Tim Wu · CC BY-SA'},{image:L('the-bund-shanghai.jpg'),label:'Banking district',chinese:'银行区',prompt:'Ask which counter handles your account.',credit:'Wikimedia Commons'}],
};

const scene=(image:string,label:string,chinese:string,prompt:string,credit='Wikimedia Commons'):ChapterScene=>({image,label,chinese,prompt,credit});
chapterScenes.apartment=[scene(L('shenzhen-bay.jpg'),'Modern apartment district','住宅小区','Ask security for the correct building.'),scene(L('pingjiang-suzhou.jpg'),'Traditional lane home','老街住宅','Describe the address and nearby lane.'),scene(L('canton-tower.jpg'),'High-rise living','高层住宅','Ask which floor the apartment is on.'),scene(L('west-lake-hangzhou.jpg'),'Lakeside neighborhood','湖边小区','Discuss rent and the view.'),scene(M,'Metro commute home','通勤回家','Explain how far the apartment is from the station.')];
chapterScenes.delivery=[scene(L('hongya-chongqing.jpg'),'Food delivery pickup','外卖取餐','Confirm the order number and pickup point.'),scene(L('shenzhen-bay.jpg'),'Office delivery','公司快递','Tell the courier which building to enter.'),scene(L('pingjiang-suzhou.jpg'),'Lane address','巷子地址','Describe a hard-to-find doorway.'),scene(D,'Tracking information','物流信息','Read the delivery status and estimated time.'),scene(L('canton-tower.jpg'),'Parcel locker','快递柜','Use a pickup code at the parcel locker.')];
chapterScenes.workplace=[scene(L('shenzhen-bay.jpg'),'Technology office','科技公司','Introduce your role to a new teammate.'),scene(L('canton-tower.jpg'),'Client meeting','客户会议','Confirm the meeting room and agenda.'),scene(T,'Business trip','出差','Discuss a work trip on the train.'),scene(L('west-lake-hangzhou.jpg'),'Team retreat','团队活动','Make a plan with coworkers.'),scene(L('the-bund-shanghai.jpg'),'Financial district','商务区','Arrange an appointment downtown.')];
chapterScenes.rail=[scene(T,'High-speed train cabin','高铁车厢','Find your carriage and seat.'),scene(D,'Departure board','列车信息','Check the train number and platform.'),scene(M,'Station transfer','站内换乘','Follow signs to the next platform.'),scene(A,'Rail-air connection','空铁联运','Plan the transfer to the airport.'),scene(L('terracotta-xian.jpg'),'Arrival in Xi’an','到达西安','Leave the station and find local transport.')];
chapterScenes.emergency=[scene(A,'Emergency help desk','紧急服务台','Explain what happened and ask for help.'),scene(M,'Station assistance','地铁求助','Contact staff on the platform.'),scene(L('shenzhen-bay.jpg'),'Calling for help','紧急电话','Give a clear location by phone.'),scene(L('west-lake-hangzhou.jpg'),'Lost item report','失物登记','Describe a lost bag accurately.'),scene(L('temple-heaven.jpg'),'Park first aid','急救站','Ask where the nearest first-aid point is.')];
chapterScenes['public-services']=[scene(L('canton-tower.jpg'),'Public service hall','政务大厅','Choose the correct counter and queue number.'),scene(A,'Document check','证件检查','Present the required identification.'),scene(D,'Appointment screen','预约信息','Confirm your appointment time.'),scene(L('shenzhen-bay.jpg'),'City services','城市服务','Ask how to submit a form online.'),scene(L('fuzimiao-nanjing.jpg'),'Local district office','社区办事处','Request directions to a local office.')];
chapterScenes.fitness=[scene(L('temple-heaven.jpg'),'Community exercise','社区锻炼','Join a warm-up in the park.'),scene(L('shenzhen-bay.jpg'),'Waterfront run','海边跑步','Discuss pace, distance, and recovery.'),scene(L('west-lake-hangzhou.jpg'),'Morning walk','晨练','Talk about a healthy routine.'),scene(L('zhangjiajie.jpg'),'Trail training','步道训练','Prepare for a longer climb.'),scene(L('chengdu-panda.jpg'),'Rest day','休息日','Explain soreness and recovery.')];
chapterScenes.festivals=[scene(L('fuzimiao-nanjing.jpg'),'Lantern festival','灯会','Buy a lantern and ask about the parade.'),scene(L('hongya-chongqing.jpg'),'Festival night market','节日夜市','Order a seasonal snack.'),scene(L('pingjiang-suzhou.jpg'),'Traditional performance','传统表演','Ask when the next show starts.'),scene(L('harbin-ice.jpg'),'Winter festival','冰雪节','Discuss tickets and warm clothing.'),scene(L('temple-heaven.jpg'),'Holiday temple visit','节日参观','Learn a holiday greeting.')];
chapterScenes.technology=[scene(L('shenzhen-bay.jpg'),'Technology park','科技园','Describe an app feature to a teammate.'),scene(L('canton-tower.jpg'),'Product showcase','产品展示','Ask a technical question during a demo.'),scene(T,'Mobile work','移动办公','Connect a device and join a call.'),scene(D,'Data display','数据屏幕','Read system status and alerts.'),scene(L('the-bund-shanghai.jpg'),'Smart city','智慧城市','Discuss how technology changes daily life.')];
chapterScenes.gym=[
  {image:'/sports-scenes/gym-ningbo.jpg',label:'University fitness center',chinese:'大学健身房',prompt:'Ask a trainer how to adjust a machine safely.',credit:'University of Nottingham Ningbo China · Wikimedia Commons',source:commons('Gym_at_the_University_of_Nottingham_Ningbo_China.jpg')},
  {image:'/sports-scenes/gym-heyuan-cardio.jpg',label:'Cardio equipment zone',chinese:'有氧器械区',prompt:'Choose a treadmill speed and training duration.',credit:'Guangdong fitness room · Wikimedia Commons',source:commons('GD_廣東_Guangdong_河源市_HeYuan_越王大道_YueWang_Avenue_Double_Tree_by_Hilton_Hotel_fittness_gym_room_center_n_machines_April_2026_N13P_02.jpg')},
  {image:'/sports-scenes/gym-heyuan-strength.jpg',label:'Strength machine circuit',chinese:'力量器械区',prompt:'Ask how many sets and repetitions to complete.',credit:'Guangdong fitness room · Wikimedia Commons',source:commons('GD_廣東_Guangdong_河源市_HeYuan_越王大道_YueWang_Avenue_Double_Tree_by_Hilton_Hotel_fittness_gym_room_center_n_machines_April_2026_N13P_03.jpg')},
  {image:'/sports-scenes/gym-heyuan-weights.jpg',label:'Free-weight training',chinese:'自由重量训练',prompt:'Request a lighter weight and check your form.',credit:'Guangdong fitness room · Wikimedia Commons',source:commons('GD_廣東_Guangdong_河源市_HeYuan_越王大道_YueWang_Avenue_Double_Tree_by_Hilton_Hotel_fittness_gym_room_center_n_machines_April_2026_N13P_04.jpg')},
  {image:'/sports-scenes/gym-heyuan-recovery.jpg',label:'Cool-down and recovery',chinese:'放松恢复区',prompt:'Talk about stretching, hydration, and recovery time.',credit:'Guangdong fitness room · Wikimedia Commons',source:commons('GD_廣東_Guangdong_河源市_HeYuan_越王大道_YueWang_Avenue_Double_Tree_by_Hilton_Hotel_fittness_gym_room_center_n_machines_April_2026_N13P_05.jpg')},
];
chapterScenes.basketball=[
  {image:'/sports-scenes/basketball-lishui.jpg',label:'Lishui University courts',chinese:'丽水学院篮球场',prompt:'Invite classmates to join a half-court game.',credit:'Huangdan2060 · Wikimedia Commons',source:commons('Basketball_court,_Lishui_University.jpg')},
  {image:'/sports-scenes/basketball-hunan.jpg',label:'Hunan university court',chinese:'湖南大学篮球场',prompt:'Choose teams and explain player positions.',credit:'Huangdan2060 · CC0',source:commons('Basketball_court,_Hunan_University_of_Chinese_Medicine.jpg')},
  {image:'/sports-scenes/basketball-xiangtan.jpg',label:'Xiangtan campus practice',chinese:'湘潭大学训练场',prompt:'Count successful shots and encourage a teammate.',credit:'Wikimedia Commons',source:commons('Basketball_court,_Xiangtan_University.jpg')},
  {image:'/sports-scenes/basketball-xiangtan-game.jpg',label:'Full-court training',chinese:'全场训练',prompt:'Call for a pass and organize the next play.',credit:'Wikimedia Commons',source:commons('Basketball_court,_Xiangtan_University,_7_April_2020.jpg')},
  {image:'/sports-scenes/basketball-beijing.jpg',label:'Beijing neighborhood game',chinese:'北京街区球赛',prompt:'Discuss the score and the final possession.',credit:'Filipe Fortes · Creative Commons',source:commons('Wangfujingbasketball.jpg')},
];
chapterScenes.badminton=[
  {image:'/sports-scenes/badminton-tin-fu.jpg',label:'Tin Fu badminton courts',chinese:'天富苑羽毛球场',prompt:'Ask whether a court is available for one hour.',credit:'Prosperity Horizons · CC BY-SA 4.0',source:commons('Tin_Fu_Court_Badminton_Court.jpg')},
  {image:'/sports-scenes/badminton-tin-ching.jpg',label:'Tin Ching community court',chinese:'天晴邨羽毛球场',prompt:'Borrow a racket and confirm the service line.',credit:'Exploringlife · CC BY-SA 4.0',source:commons('Tin_Ching_Estate_Badminton_Court.jpg')},
  {image:'/sports-scenes/badminton-yung-ming.jpg',label:'Yung Ming court practice',chinese:'雍明苑羽毛球场',prompt:'Choose partners and decide the doubles service order.',credit:'Prosperity Horizons · CC BY-SA 4.0',source:commons('Yung_Ming_Court_Badminton_Court.jpg')},
  {image:'/sports-scenes/badminton-choi-tak.jpg',label:'Choi Tak footwork drill',chinese:'彩德邨步法训练',prompt:'Follow movement instructions from corner to corner.',credit:'Wikimedia Commons · CC BY-SA',source:commons('Choi_Tak_Estate_Badminton_Court.jpg')},
  {image:'/sports-scenes/badminton-sun-tin-wai.jpg',label:'Sun Tin Wai friendly match',chinese:'新田围友谊赛',prompt:'Keep score and congratulate the winner naturally.',credit:'Wikimedia Commons · Creative Commons',source:commons('Sun_Tin_Wai_Estate_Badminton_Court_202011.jpg')},
];

// Only galleries that passed a manual relevance review are promoted from the
// licensed importer. Remaining chapters retain their hand-curated scenes until
// a replacement set passes the same review.
const reviewedLicensedChapters=['arrival','hotel','restaurant','shopping','campus','coffee','sightseeing','payments','rail'] as const;
for(const id of reviewedLicensedChapters)chapterScenes[id]=(licensedAdventureScenes[id] as ChapterScene[]);
