export type CourseStoryLesson = {
  level: 4 | 5 | 6;
  lesson: number;
  volume: '上' | '下';
  chinese: string;
  english: string;
};

const lessons = (level:4|5|6, split:number, items:[string,string][]):CourseStoryLesson[] =>
  items.map(([chinese,english],index)=>({level,lesson:index+1,volume:index+1<=split?'上':'下',chinese,english}));

export const hsk4CourseStories=lessons(4,10,[
  ['简单的爱情','Simple Love'],
  ['真正的朋友','A True Friend'],
  ['经理对我印象不错','I Made a Good Impression on the Manager'],
  ['不要太着急赚钱','Do Not Be Too Anxious to Make Money'],
  ['只买对的，不买贵的','Buy the Right One, Not the Expensive One'],
  ['一分钱一分货','The Higher the Price, the Better the Quality'],
  ['最好的医生是自己','The Best Doctor Is Yourself'],
  ['生活中不缺少美','Beauty Is Not Rare in Life'],
  ['阳光总在风雨后','The Sun Will Shine After the Storm'],
  ['幸福的标准','Standards of Happiness'],
  ['读书好，读好书，好读书','It Is Good to Read, Read Good Books, and Love Reading'],
  ['用心发现世界','Discover the World with Your Heart'],
  ['喝着茶看京剧','Drink Tea While Watching Beijing Opera'],
  ['保护地球母亲','Protect Our Mother Earth'],
  ['教育孩子的艺术','The Art of Educating Children'],
  ['生活可以更美好','Life Can Be Better'],
  ['人与自然','Humans and Nature'],
  ['科技与世界','Science, Technology, and the World'],
  ['生活的味道','The Taste of Life'],
  ['路上的风景','The View Along the Way'],
]);

export const hsk5CourseStories=lessons(5,18,[
  ['爱的细节','Details of Love'],
  ['留串钥匙给父母','Leaving a Bunch of Keys to Our Parents'],
  ['人生有选择，一切可改变','Having Choices in Life Makes Change Possible'],
  ['子路背米','Zilu Carrying Rice'],
  ['济南的泉水','Spring Water in Jinan'],
  ['除夕的由来','The Origin of Chuxi'],
  ['成语故事两则','Two Idiom Stories'],
  ['“朝三暮四”的古今义','The Ancient and Modern Meanings of “Three at Dawn and Four at Dusk”'],
  ['别样鲁迅','The Lu Xun You Do Not Know'],
  ['争论的奇迹','The Miracle of Debate'],
  ['闹钟的危害','The Harm of Alarm Clocks'],
  ['海外用户玩儿微信','Overseas Users of WeChat'],
  ['剪掉生活的“篮底”','Cutting Off the “Bottom of the Basket” in Life'],
  ['北京的四合院','Quadrangle Courtyards in Beijing'],
  ['纸上谈兵','Being an Armchair Strategist'],
  ['体重与节食','Weight and Diet'],
  ['在最美好的时刻离开','Leaving at the Best Moment'],
  ['抽象艺术美不美','Is Abstract Art Beautiful?'],
  ['家乡的萝卜饼','Turnip Pancakes in My Hometown'],
  ['小人书摊','Picture-story Book Stalls'],
  ['汉字叔叔：一个美国人的汉字情缘','Uncle Hanzi: An American’s Love for Chinese Characters'],
  ['阅读与思考','Reading and Thinking'],
  ['放手','Letting Go'],
  ['支教行动','Volunteer Teaching'],
  ['给自己加满水','Adding Up the Load on Yourself'],
  ['你属于哪一种“忙”','Which Kind of “Busy” Person Are You?'],
  ['下棋','Playing Chess'],
  ['最受欢迎的毕业生','The Most Popular Graduate'],
  ['培养对手','Training Your Rivals'],
  ['竞争让市场更高效','Competition Makes the Market More Efficient'],
  ['登门槛效应','The Foot-in-the-door Effect'],
  ['身边的环保','Protecting the Environment Around Us'],
  ['以堵治堵——缓解交通有妙招','Treating Congestion with Congestion'],
  ['鸟儿的护肤术','How Birds Take Care of Their Feathers'],
  ['植物会出汗','Plants Also Sweat'],
  ['老舍与养花','Lao She and His Flowers'],
]);

export const hsk6CourseStories=lessons(6,20,[
  ['孩子给我们的启示','An Epiphany from Children'],
  ['父母之爱','Love of Parents'],
  ['一盒月饼','A Box of Mooncakes'],
  ['完美的胜利','A Perfect Victory'],
  ['学一门外语需要理由吗','Do We Need a Reason to Learn a Foreign Language?'],
  ['当好职场插班生','Be a Good Transfer Student in the Workplace'],
  ['我的人生我做主','I Am the Master of My Own Life'],
  ['遇见原来的我','Meeting the Old Me'],
  ['不用手机的日子','A Day Without a Cell Phone'],
  ['全球化视野中的中国饮食','Chinese Food in the Global Context'],
  ['我不在时，猫在干什么','What Do the Cats Do When I Am Not Home?'],
  ['我们都爱白噪音','We All Love White Noise'],
  ['从旅游指南看世事变迁','How Travel Guides Reflect Changes in the World'],
  ['背着电饭锅拍北极','Photographing the North Pole with a Rice Cooker'],
  ['山脉上的雕刻','Sculptures on the Mountain Range'],
  ['徐健和他的野生动物摄影师们','Xu Jian and His Wildlife Photographers'],
  ['小动物眼中的慢世界','The Slow World in Small Animals’ Eyes'],
  ['神奇的丝瓜','The Magical Towel Gourd'],
  ['无阳光的深海世界','The Deep Sea Without Sunshine'],
  ['金鸡窝','The Golden Henhouse'],
  ['未来商店','Future Shops'],
  ['2050年的汽车什么样','What Will Cars Be Like in 2050?'],
  ['大数据时代','The Big Data Era'],
  ['体育明星们的离奇遭遇','Sports Stars’ Strange Experiences'],
  ['草船借箭','Borrowing Arrows with Thatched Boats'],
  ['奇异的灯光','The Extraordinary Light'],
  ['完璧归赵','Returning the Jade Intact to Zhao'],
  ['高山流水遇知音','The Friendship Between Yu Boya and Zhong Ziqi'],
  ['“笑”的备忘录','A Memorandum of Laughing'],
  ['你睡好了吗','Did You Sleep Well?'],
  ['运动的学问','Knowledge of Physical Activity'],
  ['有时，不妨悲伤','Sometimes It Is Good to Be Sad'],
  ['怀念慢生活','Cherishing the Memory of Slow Life'],
  ['为文物而生的人','A Person Born for Cultural Relics'],
  ['走近木版年画','Approaching Woodblock New Year Pictures'],
  ['中国古代书院','Ancient Chinese Academies'],
  ['警察的故事','Stories of Policemen'],
  ['慧眼捕捉商机','Finding Business Opportunities with Insight'],
  ['互联网时代的生活','Life in the Internet Era'],
  ['人类超能力会改变世界纪录吗','Will Superhuman Powers Change World Records?'],
]);

export const completeCourseStoryCatalog=[...hsk4CourseStories,...hsk5CourseStories,...hsk6CourseStories];
