"use client";

const toneHints: Record<string,string> = { 你:'nǐ · tone 3',好:'hǎo · tone 3',我:'wǒ · tone 3',们:'men · neutral',用:'yòng · tone 4',算:'suàn · tone 4',法:'fǎ · tone 3',解:'jiě · tone 3',决:'jué · tone 2',问:'wèn · tone 4',题:'tí · tone 2',可:'kě · tone 3',以:'yǐ · tone 3',去:'qù · tone 4',哪:'nǎ · tone 3',里:'lǐ · tone 3',吗:'ma · neutral',请:'qǐng · tone 3',帮:'bāng · tone 1',忙:'máng · tone 2' };

export function SyllableToneFeedback({ target, matched }: { target:string; matched:{character:string;matched:boolean}[] }) {
  return <div className="syllable-tone-feedback" aria-label={`Syllable feedback for ${target}`}><header><strong>Syllable & tone guide</strong><small>{target}</small></header><div>{matched.filter((item)=>/[\u3400-\u9fff]/.test(item.character)).map((item,index)=>{const hint=toneHints[item.character]??'tone: listen again';const sandhi=index<matched.length-1&&hint.includes('tone 3')&&(toneHints[matched[index+1]?.character]??'').includes('tone 3');return <span className={item.matched?'matched':'missed'} key={`${item.character}-${index}`}><b>{item.character}</b><em>{hint}{sandhi?' · 3→2 change':''}</em><small>{item.matched?'recognized':'repeat this syllable'}</small></span>})}</div><p>This marks syllables the device did not recognize and shows the expected lexical tone. It is a practice guide, not laboratory pitch measurement.</p></div>;
}

export function ProgressSnapshotCharts({ mastered, fading, listening, speaking, readiness, weekly }: { mastered:number; fading:number; listening:number; speaking:number; readiness:number; weekly:number[] }) {
  const max = Math.max(1, ...weekly);
  return <section className="progress-snapshot"><header><small>LEARNING HEALTH</small><h2>Progress that means something</h2><p>Memory, skill accuracy, time, and readiness—separate from XP.</p></header><div className="progress-snapshot-grid"><article><span>掌</span><strong>{mastered}</strong><small>words mastered</small></article><article><span>忘</span><strong>{fading}</strong><small>starting to fade</small></article><article className="accuracy-chart"><b>Listening <em>{listening}%</em></b><i><span style={{width:`${listening}%`}} /></i><b>Speaking <em>{speaking}%</em></b><i><span style={{width:`${speaking}%`}} /></i></article><article className="readiness-ring" style={{'--readiness':`${readiness * 3.6}deg`} as React.CSSProperties}><div><strong>{readiness}%</strong><small>HSK readiness</small></div></article><article className="weekly-bars"><strong>Weekly study</strong><div>{weekly.map((value,index)=><span key={index} title={`${value} min`}><i style={{height:`${Math.max(8,(value/max)*100)}%`}}/><small>{['M','T','W','T','F','S','S'][index]}</small></span>)}</div></article></div></section>;
}
